# Generated by Django 3.2.4 on 2021-07-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=30, verbose_name='O seu Nome ')),
                ('explicito', models.CharField(default='', max_length=30, verbose_name='O site encontra-se explicíto relativamente ao assunto que é tratado? ')),
                ('clareza', models.CharField(default=3, max_length=10)),
                ('precisao', models.CharField(default=3, max_length=10)),
                ('originalidade', models.CharField(default=3, max_length=10)),
                ('design', models.IntegerField(default=3, verbose_name='Avaliação no design (sendo 1 o pior e 5 o melhor)')),
                ('rigor', models.IntegerField(default=3, verbose_name='Avaliação no rigor (sendo 1 o pior e 5 o melhor)')),
                ('amplitude', models.IntegerField(default=50, verbose_name='Como classifica o nosso website quanto à amplitude (0 a 100)?')),
                ('profundidade', models.IntegerField(default=50, verbose_name='Como classifica o nosso website quanto à profundidade (0 a 100)?')),
                ('navegacao', models.IntegerField(default=50, verbose_name='Qual a percentagem de facilidade de navegação nas várias páginas do web site? ')),
                ('feedBack', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Your name: ')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=18)),
                ('dataCriacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pontos', models.IntegerField(default=0)),
                ('nome', models.CharField(default='', max_length=30, verbose_name='Your name: ')),
                ('p1', models.CharField(default='', max_length=40)),
                ('p2', models.CharField(default='', max_length=40)),
                ('p3', models.CharField(default='', max_length=40)),
                ('p4', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='', max_length=40)),
                ('p5', models.CharField(choices=[('20,02', '20,02'), ('11,92', '11,92'), ('10,82', '10,82')], default='', max_length=40)),
                ('p6', models.IntegerField(default=0)),
                ('p7', models.IntegerField(default=0)),
                ('p8', models.IntegerField(default=0)),
                ('p9', models.CharField(default='', max_length=40)),
                ('p10', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30, verbose_name='O seu Nome ')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.comentario')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.contacto')),
                ('quizz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.quizz')),
            ],
        ),
    ]
